package com.leonell.android.composefolderscanner.cs108library

enum class HostCmdResponseTypes {
   NULL, TYPE_COMMAND_BEGIN, TYPE_COMMAND_END, TYPE_18K6C_INVENTORY, TYPE_18K6C_INVENTORY_COMPACT, TYPE_18K6C_TAG_ACCESS, TYPE_ANTENNA_CYCLE_END, TYPE_COMMAND_ACTIVE, TYPE_COMMAND_ABORT_RETURN
}